### ISSUE TITLE
Suggesting eReefs CDL for netCDF-LD encoding example

### ISSUE THREAD

**Issue by jyucsiro** [binary-array-ld/bald#10]
Suggest using an example from eReefs for a candidate CDL for encoding netCDF-LD.

'eta' might be a good test case where there are CF standard name, and the ereefs conventions for *_id attributes.
[gbr4.zip](https://github.com/binary-array-ld/bald/files/553200/gbr4.zip)

**Comment by marqh** [comment]
I have pushed up code which enables us to store CDL files in the repository (small ones) and use them for testing the code, as well as for communication

I hope this helps

**Comment by marqh** [comment]
* if you would like a new CDL file included in this collection, please create a Pull Request, with a new file in here:
 * https://github.com/binary-array-ld/bald/tree/master/lib/bald/tests/integration/CDL
  * please keep the file sizes small with respect to data
  * lots of metadata is fine, that is kind of the point
 * and an additional test case in here:
  * https://github.com/binary-array-ld/bald/blob/master/lib/bald/tests/integration/test_cdl.py

that way the testing will report on the file and we'll learn things

**Comment by jyucsiro** [comment]
Done and added to https://github.com/binary-array-ld/bald/tree/master/lib/bald/tests/integration/CDL
