### ISSUE TITLE
prefix identification

### ISSUE THREAD

**Issue by marqh** [binary-array-ld/bald#2]
in #1 I have proposed a syntax for defining a prefix and a prefixed attribute name or value within a binary file.

I propose the use of `__` as a prefix separator.  In RDF `:` is commonly used, but this is a reserved character in file formats and programming languages, so unsuitable for direct adoption.

The `__` syntax can be combined with an explicit prefix as an attribute, e.g.:

```
bald__ = 'http://binary-array-ld.net/experimental/'
```
this enable an attribute definition:
```
bald__references
```
to be interpreted as
```
http://binary-array-ld.net/experimental/references
```

Thus, a shortened form of URI, similar to use in RDF serialisations, may be used in datasets and programming APIs, providing the prefix is explicitly defined within a relevant scope (akin to RDF usage).

**Comment by jyucsiro** [comment]
I like this approach of mirroring RDF ':' with 2x '-' as syntax for this. We had trouble figuring out how to do this for example in netCDF headers, so this approach could work for that example.

**Comment by marqh** [comment]
#9 has an implementation which addresses this issue, I believe; please add comments to that PR as to its suitability

Please add further comments to this issue where #9 does not meets this requirement

**Comment by marqh** [comment]
#9 is now merged, so I am closing this issue.  further discussion on prefixes is (of course) welcome
